import { ReactNode, useEffect, Fragment } from "react"
import Head from "next/head"
import Script from 'next/script'

interface AuthProps {
    children: ReactNode
}

export default function Auth(props: AuthProps) {
    useEffect(() => {
        document.body.classList.add('hold-transition')
        document.body.classList.add('login-page')
    }, [])

    return(
        <Fragment>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback"
                />
                <link
                    rel="stylesheet"
                    href="/assets/vendor/fontawesome/css/all.css"
                />
                <link
                    rel="stylesheet"
                    href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
                />
                <link
                    rel="stylesheet"
                    href="/assets/vendor/adminlte/icheck-bootstrap.min.css"
                />
                <link
                    rel="stylesheet"
                    href="/assets/vendor/adminlte/adminlte.min.css"
                />
            </Head>

            { props.children }

            <Script strategy="beforeInteractive" src="/assets/vendor/adminlte/jquery.min.js" />
            <Script strategy="beforeInteractive" src="/assets/vendor/adminlte/bootstrap.bundle.min.js" />
            <Script strategy="beforeInteractive" src="/assets/vendor/adminlte/adminlte.min.js" />
        </Fragment>
    )
}