import React, { ReactNode, useEffect, Fragment } from "react"
import Head from "next/head"
import Script from 'next/script'
import { getCookie, removeCookies } from 'cookies-next'
import axios from "../../configs/axios"
import Swal from "sweetalert2"


interface DashboardProps {
    children: ReactNode
}

class Dashboard extends React.Component {
    state = {
        settings: [
            'roles',
            'permissions',
            'users'
        ]
    }

    componentDidMount(){
        document.body.classList.add('hold-transition')
        document.body.classList.add('sidebar-mini')
        document.body.classList.add('layout-fixed')
    }

    handleLogout = (e: { preventDefault: () => void }) => {
        e.preventDefault()

        const token = getCookie('token')
        axios.post(`/auth/logout`, { token })
            .then(res => {
                if (res.data.status === 'success') {
                    removeCookies('token')
                    window.location.href = '/'
                }
            })
            .catch(error => {
                if (error.response.data.error) {
                    Swal.fire(
                        'Failed',
                        `${error.response.data.error}`,
                        'error'
                    )
                }
            })
    }

    render() {
        return(
            <Fragment>
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link
                        rel="stylesheet"
                        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback"
                    />
                    <link
                        rel="stylesheet"
                        href="/assets/vendor/fontawesome/css/all.css"
                    />
                    <link
                        rel="stylesheet"
                        href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
                    />
                    <link
                        rel="stylesheet"
                        href="/assets/vendor/adminlte/icheck-bootstrap.min.css"
                    />
                    <link
                        rel="stylesheet"
                        href="/assets/vendor/adminlte/adminlte.min.css"
                    />
                </Head>

                <div className="wrapper">
                    <nav className="main-header navbar navbar-expand navbar-white navbar-light">
                        <ul className="navbar-nav">
                            <li className="nav-item">
                                <a className="nav-link" data-widget="pushmenu" href="#">
                                    <i className="fas fa-bars"></i>
                                </a>
                            </li>
                            <li className="nav-item d-inline-block">
                                <a href="/" className="nav-link">Home</a>
                            </li>
                            <li className="nav-item d-none d-sm-inline-block">
                                <a href="#" className="nav-link">Contact</a>
                            </li>
                        </ul>
                        
                        <form className="form-inline ml-3">
                            <div className="input-group input-group-sm">
                                <input className="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search"/>
                                <div className="input-group-append">
                                <button className="btn btn-navbar" type="submit">
                                    <i className="fas fa-search"></i>
                                </button>
                                </div>
                            </div>
                        </form>
                        
                        <ul className="navbar-nav ml-auto">
                            <li className="nav-item dropdown">
                                <a className="nav-link" data-toggle="dropdown" href="#">
                                    <i className="far fa-comments"></i>
                                    <span className="badge badge-danger navbar-badge">
                                        10
                                    </span>
                                </a>
                                <div className="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                                    <a href="#" className="dropdown-item">
                                        <div className="media">
                                            <div className="media-body">
                                                <h3 className="dropdown-item-title">
                                                    admin@mail.com
                                                    <span className="float-right text-sm text-danger"><i className="fas fa-star"></i></span>
                                                </h3>
                                                <p className="text-sm">subject</p>
                                                <p className="text-sm text-muted">
                                                    <i className="far fa-clock mr-1"></i> 20/12/2021
                                                </p>
                                            </div>
                                        </div>
                                    </a>
                                    <div className="dropdown-divider"></div>
                                    <a href="#" className="dropdown-item dropdown-footer">See All Messages</a>
                                </div>
                            </li>
                            
                            <li className="nav-item dropdown">
                                <a className="nav-link" data-toggle="dropdown" href="#">
                                    <i className="far fa-bell"></i>
                                    <span className="badge badge-warning navbar-badge">
                                        20
                                    </span>
                                </a>
                                <div className="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                                    <span className="dropdown-item dropdown-header">
                                        21 Notifications
                                    </span>
                                    <div className="dropdown-divider"></div>
                                        <a href="/user/lsp_contact" className="dropdown-item">        
                                            <i className="fas fa-envelope mr-2"></i> 22 new messages   
                                        </a>
                                        <div className="dropdown-divider"></div>
                                    
                                        <a href="/user/event_landing" className="dropdown-item">
                                            <i className="fas fa-users mr-2"></i> 3 event requests
                                        </a>
                                        <div className="dropdown-divider"></div>
                                    <div className="dropdown-divider"></div>
                                    <a href="#" className="dropdown-item">
                                        <i className="fas fa-file mr-2"></i> 3 new reports
                                        <span className="float-right text-muted text-sm">2 days</span>
                                    </a>
                                    <a href="#" className="dropdown-item dropdown-footer">See All Notifications</a>
                                </div>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                                    <i className="fas fa-th-large"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>

                    <aside className="main-sidebar sidebar-dark-primary elevation-4">
                        <a href="/auth/dashboard" className="brand-link">
                            <img src="/assets/images/logo.png" alt="logo" className="brand-image img-circle elevation-3"/>
                            <span className="brand-text font-weight-light">Beauty</span>
                        </a>

                        <div className="sidebar">
                            <div className="user-panel mt-3 pb-3 mb-3 d-flex">
                                <div className="image">
                                    <img src="/assets/images/woman.png" className="img-circle elevation-2" alt="avatar"/>
                                </div>
                                <div className="info">
                                    <a href="#" className="d-block">username</a>
                                </div>
                            </div>

                            <nav className="mt-2">
                                <ul className="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
                                    <li className="nav-item">
                                        <a href="/auth/dashboard" className="nav-link">
                                            <i className="nav-icon fas fa-tachometer-alt"></i>
                                            <p>Dashboard</p>
                                        </a>
                                    </li>
                                    <li className="nav-item has-treeview">
                                        <a href="#" className="nav-link">
                                            <i className="nav-icon fas fa-cubes"></i>
                                            <p>
                                                Products
                                                <i className="right fa fa-angle-left"></i>
                                            </p>
                                        </a>
                                        <ul className="nav nav-treeview">
                                            <li className="nav-item">
                                                <a href="/categories" className="nav-link">
                                                    <i className="nav-icon fas fa-layer-group"></i>
                                                    <p>Category</p>
                                                </a>
                                            </li>
                                            <li className="nav-item">
                                                <a href="/product/attribute" className="nav-link">
                                                    <i className="nav-icon fas fa-list"></i>
                                                    <p>Attribute</p>
                                                </a>
                                            </li>
                                            <li className="nav-item">
                                                <a href="/product" className="nav-link">
                                                    <i className="nav-icon fas fa-archive"></i>
                                                    <p>Product</p>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li className="nav-item has-treeview">
                                        <a href="#" className="nav-link">
                                            <i className="nav-icon fas fa-shopping-cart"></i>
                                            <p>
                                                Orders
                                                <i className="right fa fa-angle-left"></i>
                                            </p>
                                        </a>
                                        <ul className="nav nav-treeview">
                                            <li className="nav-item">
                                                <a href="/orders" className="nav-link">
                                                    <i className="nav-icon fas fa-truck-loading"></i>
                                                    <p>Order</p>
                                                </a>
                                            </li>
                                            <li className="nav-item">
                                                <a href="/orders/trashed" className="nav-link">
                                                    <i className="nav-icon fas fa-trash"></i>
                                                    <p>Trash</p>
                                                </a>
                                            </li>
                                            <li className="nav-item">
                                                <a href="shipments" className="nav-link">
                                                    <i className="nav-icon fas fa-truck-moving"></i>
                                                    <p>Shipment</p>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li className="nav-item has-treeview">
                                        <a href="#" className="nav-link">
                                            <i className="nav-icon fas fa-folder"></i>
                                            <p>
                                                Reports
                                                <i className="right fa fa-angle-left"></i>
                                            </p>
                                        </a>
                                        <ul className="nav nav-treeview">
                                            <li className="nav-item">
                                                <a href="/reports/revenue" className="nav-link">
                                                    <i className="nav-icon fas fa-dollar-sign"></i>
                                                    <p>Revenue</p>
                                                </a>
                                            </li>
                                            <li className="nav-item">
                                                <a href="/reports/product" className="nav-link">
                                                    <i className="nav-icon fas fa-cubes"></i>
                                                    <p>Product</p>
                                                </a>
                                            </li>
                                            <li className="nav-item">
                                                <a href="/reports/inventory" className="nav-link">
                                                    <i className="nav-icon fas fa-dolly-flatbed"></i>
                                                    <p>Inventory</p>
                                                </a>
                                            </li>
                                            <li className="nav-item">
                                                <a href="/reports/payment" className="nav-link">
                                                    <i className="nav-icon fas fa-money-bill-wave"></i>
                                                    <p>Payment</p>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li className="nav-item has-treeview">
                                        <a href="#" className="nav-link">
                                            <i className="nav-icon fas fa-cogs"></i>
                                            <p>
                                                Settings
                                                <i className="right fas fa-angle-left"></i>
                                            </p>
                                        </a>
                                        <ul className="nav nav-treeview">
                                            <li className="nav-item has-treeview">
                                                <a href="#" className="nav-link">
                                                    <i className="fas fa-users-cog nav-icon"></i>
                                                    <p>
                                                        <span>User & Role</span>
                                                        <i className="right fas fa-angle-left"></i>
                                                    </p>
                                                </a>
                                                <ul className="nav nav-treeview">
                                                    <li className="nav-item">
                                                        <a href="/auth/roles" className="nav-link">
                                                            <i className="fas fa-user-shield nav-icon"></i>
                                                            <p>Roles</p>
                                                        </a>
                                                    </li>
                                                    <li className="nav-item">
                                                        <a href="/auth/permissions" className="nav-link">
                                                            <i className="fas fa-user-cog nav-icon"></i>
                                                            <p>Permissions</p>
                                                        </a>
                                                    </li>
                                                    <li className="nav-item">
                                                        <a href="/auth/users" className="nav-link">
                                                            <i className="fas fa-users nav-icon"></i>
                                                            <p>Users</p>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                    <li className="nav-item">
                                        <a onClick={this.handleLogout} className="nav-link" href="#">
                                            <i className="nav-icon fas fa-power-off"></i>
                                            <p>
                                                Logout
                                            </p>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </aside>

                    { this.props.children }

                    <aside className="control-sidebar control-sidebar-dark">
                        <div className="p-3">
                            <h5>Title</h5>
                            <p>Sidebar content</p>
                        </div>
                    </aside>
                    
                    <footer className="main-footer">
                        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
                        All rights reserved.
                        <div className="float-right d-none d-sm-inline-block">
                            <b>Version</b> 3.0.0
                        </div>
                    </footer>
                </div>

                <Script strategy="beforeInteractive" src="/assets/vendor/adminlte/jquery.min.js" />
                <Script strategy="beforeInteractive" src="/assets/vendor/adminlte/bootstrap.bundle.min.js" />
                <Script strategy="beforeInteractive" src="/assets/vendor/adminlte/adminlte.min.js" />
            </Fragment>
        )
    }
}

export default Dashboard