version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./docker/mongodb:/data/db
    ports:
      - 27017:27017
    # command: mongod
    command: mongod --auth